-- Mads production schema (Postgres / Neon).
--
-- Mirrors what's currently split across ~/.mads/*.sqlite3 and ~/.mads/**/*.json:
-- chat sessions+messages (server/store.py), direct memory (memory/store.py),
-- planner projects/tasks/prompts (planner/storage.py), and the Adaptive
-- Intelligence approval queue (adaptive/storage.py). OAuth tokens are
-- deliberately NOT included here — they stay as local Fernet-encrypted
-- files under ~/.mads/auth/*.enc, since moving an encrypted secret store
-- into a shared database doesn't reduce its exposure, it just adds a new
-- network boundary to trust.

-- ── Chat sessions (server/store.py) ──────────────────────────────────────

CREATE TABLE IF NOT EXISTS sessions (
    id TEXT PRIMARY KEY,
    title TEXT NOT NULL,
    created_at DOUBLE PRECISION NOT NULL,
    updated_at DOUBLE PRECISION NOT NULL
);

CREATE TABLE IF NOT EXISTS messages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id TEXT NOT NULL REFERENCES sessions(id) ON DELETE CASCADE,
    role TEXT NOT NULL,
    text TEXT NOT NULL DEFAULT '',
    tool_calls TEXT,
    files TEXT,
    created_at DOUBLE PRECISION NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_messages_session ON messages(session_id);

-- ── Direct memory (memory/store.py) ──────────────────────────────────────

CREATE TABLE IF NOT EXISTS memories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category TEXT NOT NULL CHECK (category IN ('preference', 'project', 'decision', 'person', 'identity')),
    content TEXT NOT NULL,
    tags TEXT NOT NULL DEFAULT '',
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_memories_category ON memories(category);

-- ── Planner: projects, tasks, prompts (planner/models.py + storage.py) ──

CREATE TABLE IF NOT EXISTS projects (
    slug TEXT PRIMARY KEY,
    name TEXT NOT NULL,
    github_repo TEXT,
    folder TEXT,
    drive_folder TEXT,
    tags TEXT[] NOT NULL DEFAULT '{}',
    created_at TIMESTAMPTZ NOT NULL,
    last_active_at TIMESTAMPTZ
);

CREATE TABLE IF NOT EXISTS tasks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_slug TEXT NOT NULL REFERENCES projects(slug) ON DELETE CASCADE,
    title TEXT NOT NULL,
    description TEXT NOT NULL DEFAULT '',
    priority TEXT NOT NULL DEFAULT 'medium' CHECK (priority IN ('low', 'medium', 'high')),
    status TEXT NOT NULL DEFAULT 'open' CHECK (status IN ('open', 'in_progress', 'blocked', 'done')),
    due_date DATE,
    tags TEXT[] NOT NULL DEFAULT '{}',
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL,
    completed_at TIMESTAMPTZ
);

CREATE INDEX IF NOT EXISTS idx_tasks_project ON tasks(project_slug);
CREATE INDEX IF NOT EXISTS idx_tasks_status ON tasks(status);

-- slug is only unique WITHIN a scope (the same slug can exist as a global
-- prompt and, independently, inside any number of different projects'
-- prompt sets — mirrors the old layout of one prompts/ directory per
-- project plus one global prompts/ directory), hence the surrogate `id`
-- rather than slug itself as the primary key.
CREATE TABLE IF NOT EXISTS prompts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    slug TEXT NOT NULL,
    title TEXT NOT NULL,
    description TEXT NOT NULL DEFAULT '',
    category TEXT NOT NULL DEFAULT 'general',
    body TEXT NOT NULL,
    tags TEXT[] NOT NULL DEFAULT '{}',
    scope TEXT NOT NULL CHECK (scope IN ('global', 'project')),
    project_slug TEXT REFERENCES projects(slug) ON DELETE CASCADE,
    favorite BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL
);

-- COALESCE makes this NULL-safe: plain UNIQUE treats NULL project_slug
-- (global-scope prompts) as always distinct, which would let the same
-- global slug be inserted any number of times.
CREATE UNIQUE INDEX IF NOT EXISTS prompts_scope_unique
    ON prompts (slug, scope, COALESCE(project_slug, ''));

-- ── Adaptive Intelligence: approval queue (adaptive/models.py + storage.py) ──

CREATE TABLE IF NOT EXISTS adaptive_pending_candidates (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category TEXT NOT NULL CHECK (category IN ('preference', 'decision', 'workflow', 'constraint', 'identity')),
    statement TEXT NOT NULL,
    confidence DOUBLE PRECISION NOT NULL,
    recurrence INTEGER NOT NULL,
    source_conversation_ids TEXT[] NOT NULL DEFAULT '{}',
    contradicts TEXT[] NOT NULL DEFAULT '{}',
    status TEXT NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'approved', 'rejected')),
    created_at TIMESTAMPTZ NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_adaptive_pending_status ON adaptive_pending_candidates(status);

CREATE TABLE IF NOT EXISTS adaptive_approved_facts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category TEXT NOT NULL CHECK (category IN ('preference', 'decision', 'workflow', 'constraint', 'identity')),
    statement TEXT NOT NULL,
    confidence DOUBLE PRECISION NOT NULL,
    approved_at TIMESTAMPTZ NOT NULL,
    source_conversation_ids TEXT[] NOT NULL DEFAULT '{}'
);

CREATE TABLE IF NOT EXISTS adaptive_ledger (
    conversation_id TEXT PRIMARY KEY,
    content_hash TEXT NOT NULL,
    processed_at TIMESTAMPTZ NOT NULL,
    outcome TEXT NOT NULL CHECK (outcome IN ('gated', 'not_worth_learning', 'extracted'))
);
